version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: forkflash-app-dev
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - composer_cache:/home/appuser/.composer
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - XDEBUG_MODE=debug
      - XDEBUG_CONFIG=client_host=host.docker.internal
    networks:
      - forkflash-network
    depends_on:
      - db
      - redis
    extra_hosts:
      - "host.docker.internal:host-gateway"

  nginx:
    image: nginx:alpine
    container_name: forkflash-nginx-dev
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/development.conf:/etc/nginx/conf.d/default.conf
    networks:
      - forkflash-network
    depends_on:
      - app

  db:
    image: postgres:15-alpine
    container_name: forkflash-postgres-dev
    restart: unless-stopped
    environment:
      POSTGRES_DB: forkflash_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - forkflash-network

  redis:
    image: redis:7-alpine
    container_name: forkflash-redis-dev
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_dev_data:/data
    networks:
      - forkflash-network

  cloudbeaver:
    image: dbeaver/cloudbeaver:latest
    container_name: forkflash-cloudbeaver-dev
    restart: unless-stopped
    ports:
      - "8080:8978"
    volumes:
      - cloudbeaver_dev_data:/opt/cloudbeaver/workspace
    networks:
      - forkflash-network
    depends_on:
      - db

  mailhog:
    image: mailhog/mailhog:latest
    container_name: forkflash-mailhog-dev
    restart: unless-stopped
    ports:
      - "1025:1025"  # SMTP port
      - "8025:8025"  # Web UI port
    networks:
      - forkflash-network

  minio:
    image: minio/minio:latest
    container_name: forkflash-minio-dev
    restart: unless-stopped
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    volumes:
      - minio_dev_data:/data
    command: server /data --console-address ":9001"
    networks:
      - forkflash-network

volumes:
  postgres_dev_data:
  redis_dev_data:
  cloudbeaver_dev_data:
  minio_dev_data:
  composer_cache:

networks:
  forkflash-network:
    driver: bridge
